"""Add exercises to Stats

Revision ID: 02cd77d23a66
Revises: 6e82dbad63ea
Create Date: 2025-04-19 18:48:02.213994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02cd77d23a66'
down_revision = '6e82dbad63ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercises_answered', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('correct_exercises', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stats', schema=None) as batch_op:
        batch_op.drop_column('correct_exercises')
        batch_op.drop_column('exercises_answered')

    # ### end Alembic commands ###
