"""BlogPost's add temp author

Revision ID: 372e8a210c52
Revises: 8d91ff0d7137
Create Date: 2025-03-22 15:34:47.547531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '372e8a210c52'
down_revision = '8d91ff0d7137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('author')

    # ### end Alembic commands ###
