"""BlogPost's title is unique

Revision ID: 4a40e1b1d10a
Revises: 9d8b075593e6
Create Date: 2025-03-22 15:08:46.599688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a40e1b1d10a'
down_revision = '9d8b075593e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_blogpost_title', ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
