"""Remove color from category

Revision ID: 6e82dbad63ea
Revises: 793ecb894257
Create Date: 2025-04-01 19:49:47.669959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e82dbad63ea'
down_revision = '793ecb894257'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.VARCHAR(length=20), server_default=sa.text("'blue'"), nullable=False))

    # ### end Alembic commands ###
