"""Add is_admin to user

Revision ID: 793ecb894257
Revises: 2ebfc2f86e25
Create Date: 2025-03-22 19:05:36.054987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793ecb894257'
down_revision = '2ebfc2f86e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
