"""Add title to Paragraph

Revision ID: 8821850dd007
Revises: 9a1c25a1cbc7
Create Date: 2025-03-22 16:55:34.675762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8821850dd007'
down_revision = '9a1c25a1cbc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_paragraph', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post_paragraph', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
