"""BlogPost's add subtitle

Revision ID: 8d91ff0d7137
Revises: 4a40e1b1d10a
Create Date: 2025-03-22 15:29:01.455527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d91ff0d7137'
down_revision = '4a40e1b1d10a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtitle', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_column('subtitle')

    # ### end Alembic commands ###
