"""Add color to categories

Revision ID: 9d8b075593e6
Revises: 154effcd1e1e
Create Date: 2025-03-21 20:52:40.847685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d8b075593e6'
down_revision = '154effcd1e1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=False, server_default="blue"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('color')

    # ### end Alembic commands ###
