"""Fix Stats

Revision ID: 9f263e3d151a
Revises: 02cd77d23a66
Create Date: 2025-04-19 19:19:24.290089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f263e3d151a'
down_revision = '02cd77d23a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_stats',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('pomodoro_focus', sa.INTEGER(), nullable=False),
    sa.Column('pomodoro_breaks', sa.INTEGER(), nullable=False),
    sa.Column('exercises_answered', sa.INTEGER(), nullable=False),
    sa.Column('correct_exercises', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
